export default [
  {"sortname":"NG","name":"Nigeria","phonecode":"234"},
  {"sortname":"US","name":"United States","phonecode":"1"},
  {"sortname":"GB","name":"United Kingdom","phonecode":"44"},
  {"sortname":"AF","name":"Afghanistan","phonecode":"93"},
  {"sortname":"DZ","name":"Algeria","phonecode":"213"},
  {"sortname":"AS","name":"American Samoa","phonecode":"1684"},
  {"sortname":"AL","name":"Albania","phonecode":"355"},
  {"sortname":"AD","name":"Andorra","phonecode":"376"},
  {"sortname":"AO","name":"Angola","phonecode":"244"},
  {"sortname":"AG","name":"Antigua And Barbuda","phonecode":"1268"},
  {"sortname":"AQ","name":"Antarctica","phonecode":"0"},
  {"sortname":"AR","name":"Argentina","phonecode":"54"},
  {"sortname":"AI","name":"Anguilla","phonecode":"1264"},
  {"sortname":"AM","name":"Armenia","phonecode":"374"},
  {"sortname":"AT","name":"Austria","phonecode":"43"},
  {"sortname":"AU","name":"Australia","phonecode":"61"},
  {"sortname":"AZ","name":"Azerbaijan","phonecode":"994"},
  {"sortname":"AW","name":"Aruba","phonecode":"297"},
  {"sortname":"BS","name":"Bahamas The","phonecode":"1242"},
  {"sortname":"BB","name":"Barbados","phonecode":"1246"},
  {"sortname":"BD","name":"Bangladesh","phonecode":"880"},
  {"sortname":"BY","name":"Belarus","phonecode":"375"},
  {"sortname":"BH","name":"Bahrain","phonecode":"973"},
  {"sortname":"BE","name":"Belgium","phonecode":"32"},
  {"sortname":"BM","name":"Bermuda","phonecode":"1441"},
  {"sortname":"BJ","name":"Benin","phonecode":"229"},
  {"sortname":"BT","name":"Bhutan","phonecode":"975"},
  {"sortname":"BZ","name":"Belize","phonecode":"501"},
  {"sortname":"BO","name":"Bolivia","phonecode":"591"},
  {"sortname":"BV","name":"Bouvet Island","phonecode":"0"},
  {"sortname":"BW","name":"Botswana","phonecode":"267"},
  {"sortname":"BR","name":"Brazil","phonecode":"55"},
  {"sortname":"BA","name":"Bosnia and Herzegovina","phonecode":"387"},
  {"sortname":"IO","name":"British Indian Ocean Territory","phonecode":"246"},
  {"sortname":"BF","name":"Burkina Faso","phonecode":"226"},
  {"sortname":"BG","name":"Bulgaria","phonecode":"359"},
  {"sortname":"BI","name":"Burundi","phonecode":"257"},
  {"sortname":"CV","name":"Cape Verde","phonecode":"238"},
  {"sortname":"BN","name":"Brunei","phonecode":"673"},
  {"sortname":"KH","name":"Cambodia","phonecode":"855"},
  {"sortname":"CA","name":"Canada","phonecode":"1"},
  {"sortname":"CN","name":"China","phonecode":"86"},
  {"sortname":"CM","name":"Cameroon","phonecode":"237"},
  {"sortname":"KY","name":"Cayman Islands","phonecode":"1345"},
  {"sortname":"CF","name":"Central African Republic","phonecode":"236"},
  {"sortname":"CL","name":"Chile","phonecode":"56"},
  {"sortname":"CG","name":"Republic Of The Congo","phonecode":"242"},
  {"sortname":"TD","name":"Chad","phonecode":"235"},
  {"sortname":"CX","name":"Christmas Island","phonecode":"61"},
  {"sortname":"CC","name":"Cocos (Keeling) Islands","phonecode":"672"},
  {"sortname":"KM","name":"Comoros","phonecode":"269"},
  {"sortname":"HR","name":"Croatia (Hrvatska)","phonecode":"385"},
  {"sortname":"CD","name":"Democratic Republic Of The Congo","phonecode":"242"},
  {"sortname":"CO","name":"Colombia","phonecode":"57"},
  {"sortname":"CK","name":"Cook Islands","phonecode":"682"},
  {"sortname":"CI","name":"Cote D'Ivoire (Ivory Coast)","phonecode":"225"},
  {"sortname":"DJ","name":"Djibouti","phonecode":"253"},
  {"sortname":"CU","name":"Cuba","phonecode":"53"},
  {"sortname":"CR","name":"Costa Rica","phonecode":"506"},
  {"sortname":"DK","name":"Denmark","phonecode":"45"},
  {"sortname":"EG","name":"Egypt","phonecode":"20"},
  {"sortname":"CY","name":"Cyprus","phonecode":"357"},
  {"sortname":"DM","name":"Dominica","phonecode":"1767"},
  {"sortname":"CZ","name":"Czech Republic","phonecode":"420"},
  {"sortname":"EC","name":"Ecuador","phonecode":"593"},
  {"sortname":"ET","name":"Ethiopia","phonecode":"251"},
  {"sortname":"DO","name":"Dominican Republic","phonecode":"1809"},
  {"sortname":"SV","name":"El Salvador","phonecode":"503"},
  {"sortname":"TP","name":"East Timor","phonecode":"670"},
  {"sortname":"EE","name":"Estonia","phonecode":"372"},
  {"sortname":"GQ","name":"Equatorial Guinea","phonecode":"240"},
  {"sortname":"FI","name":"Finland","phonecode":"358"},
  {"sortname":"XA","name":"External Territories of Australia","phonecode":"61"},
  {"sortname":"ER","name":"Eritrea","phonecode":"291"},
  {"sortname":"FJ","name":"Fiji Islands","phonecode":"679"},
  {"sortname":"FK","name":"Falkland Islands","phonecode":"500"},
  {"sortname":"GA","name":"Gabon","phonecode":"241"},
  {"sortname":"FR","name":"France","phonecode":"33"},
  {"sortname":"FO","name":"Faroe Islands","phonecode":"298"},
  {"sortname":"GF","name":"French Guiana","phonecode":"594"},
  {"sortname":"TF","name":"French Southern Territories","phonecode":"0"},
  {"sortname":"GM","name":"Gambia The","phonecode":"220"},
  {"sortname":"GI","name":"Gibraltar","phonecode":"350"},
  {"sortname":"PF","name":"French Polynesia","phonecode":"689"},
  {"sortname":"GE","name":"Georgia","phonecode":"995"},
  {"sortname":"GH","name":"Ghana","phonecode":"233"},
  {"sortname":"GR","name":"Greece","phonecode":"30"},
  {"sortname":"GU","name":"Guam","phonecode":"1671"},
  {"sortname":"DE","name":"Germany","phonecode":"49"},
  {"sortname":"GL","name":"Greenland","phonecode":"299"},
  {"sortname":"GP","name":"Guadeloupe","phonecode":"590"},
  {"sortname":"GT","name":"Guatemala","phonecode":"502"},
  {"sortname":"GY","name":"Guyana","phonecode":"592"},
  {"sortname":"GD","name":"Grenada","phonecode":"1473"},
  {"sortname":"XU","name":"Guernsey and Alderney","phonecode":"44"},
  {"sortname":"GW","name":"Guinea-Bissau","phonecode":"245"},
  {"sortname":"HT","name":"Haiti","phonecode":"509"},
  {"sortname":"GN","name":"Guinea","phonecode":"224"},
  {"sortname":"HU","name":"Hungary","phonecode":"36"},
  {"sortname":"HM","name":"Heard and McDonald Islands","phonecode":"0"},
  {"sortname":"HK","name":"Hong Kong S.A.R.","phonecode":"852"},
  {"sortname":"IS","name":"Iceland","phonecode":"354"},
  {"sortname":"IQ","name":"Iraq","phonecode":"964"},
  {"sortname":"HN","name":"Honduras","phonecode":"504"},
  {"sortname":"IN","name":"India","phonecode":"91"},
  {"sortname":"IR","name":"Iran","phonecode":"98"},
  {"sortname":"IE","name":"Ireland","phonecode":"353"},
  {"sortname":"JP","name":"Japan","phonecode":"81"},
  {"sortname":"ID","name":"Indonesia","phonecode":"62"},
  {"sortname":"IL","name":"Israel","phonecode":"972"},
  {"sortname":"JM","name":"Jamaica","phonecode":"1876"},
  {"sortname":"XJ","name":"Jersey","phonecode":"44"},
  {"sortname":"KI","name":"Kiribati","phonecode":"686"},
  {"sortname":"IT","name":"Italy","phonecode":"39"},
  {"sortname":"JO","name":"Jordan","phonecode":"962"},
  {"sortname":"KE","name":"Kenya","phonecode":"254"},
  {"sortname":"KP","name":"Korea North","phonecode":"850"},
  {"sortname":"LA","name":"Laos","phonecode":"856"},
  {"sortname":"KZ","name":"Kazakhstan","phonecode":"7"},
  {"sortname":"KG","name":"Kyrgyzstan","phonecode":"996"},
  {"sortname":"KR","name":"Korea South","phonecode":"82"},
  {"sortname":"LV","name":"Latvia","phonecode":"371"},
  {"sortname":"LY","name":"Libya","phonecode":"218"},
  {"sortname":"KW","name":"Kuwait","phonecode":"965"},
  {"sortname":"LR","name":"Liberia","phonecode":"231"},
  {"sortname":"LB","name":"Lebanon","phonecode":"961"},
  {"sortname":"LI","name":"Liechtenstein","phonecode":"423"},
  {"sortname":"LS","name":"Lesotho","phonecode":"266"},
  {"sortname":"MK","name":"Macedonia","phonecode":"389"},
  {"sortname":"MO","name":"Macau S.A.R.","phonecode":"853"},
  {"sortname":"LT","name":"Lithuania","phonecode":"370"},
  {"sortname":"MG","name":"Madagascar","phonecode":"261"},
  {"sortname":"ML","name":"Mali","phonecode":"223"},
  {"sortname":"LU","name":"Luxembourg","phonecode":"352"},
  {"sortname":"MV","name":"Maldives","phonecode":"960"},
  {"sortname":"MW","name":"Malawi","phonecode":"265"},
  {"sortname":"MT","name":"Malta","phonecode":"356"},
  {"sortname":"MY","name":"Malaysia","phonecode":"60"},
  {"sortname":"MR","name":"Mauritania","phonecode":"222"},
  {"sortname":"MQ","name":"Martinique","phonecode":"596"},
  {"sortname":"XM","name":"Man (Isle of)","phonecode":"44"},
  {"sortname":"MU","name":"Mauritius","phonecode":"230"},
  {"sortname":"MH","name":"Marshall Islands","phonecode":"692"},
  {"sortname":"MD","name":"Moldova","phonecode":"373"},
  {"sortname":"FM","name":"Micronesia","phonecode":"691"},
  {"sortname":"YT","name":"Mayotte","phonecode":"269"},
  {"sortname":"MC","name":"Monaco","phonecode":"377"},
  {"sortname":"MX","name":"Mexico","phonecode":"52"},
  {"sortname":"MZ","name":"Mozambique","phonecode":"258"},
  {"sortname":"MA","name":"Morocco","phonecode":"212"},
  {"sortname":"MN","name":"Mongolia","phonecode":"976"},
  {"sortname":"MM","name":"Myanmar","phonecode":"95"},
  {"sortname":"MS","name":"Montserrat","phonecode":"1664"},
  {"sortname":"AN","name":"Netherlands Antilles","phonecode":"599"},
  {"sortname":"NP","name":"Nepal","phonecode":"977"},
  {"sortname":"NA","name":"Namibia","phonecode":"264"},
  {"sortname":"NL","name":"Netherlands The","phonecode":"31"},
  {"sortname":"NR","name":"Nauru","phonecode":"674"},
  {"sortname":"NI","name":"Nicaragua","phonecode":"505"},
  {"sortname":"NE","name":"Niger","phonecode":"227"},
  {"sortname":"NC","name":"New Caledonia","phonecode":"687"},
  {"sortname":"NZ","name":"New Zealand","phonecode":"64"},
  {"sortname":"MP","name":"Northern Mariana Islands","phonecode":"1670"},
  {"sortname":"NO","name":"Norway","phonecode":"47"},
  {"sortname":"NU","name":"Niue","phonecode":"683"},
  {"sortname":"OM","name":"Oman","phonecode":"968"},
  {"sortname":"NF","name":"Norfolk Island","phonecode":"672"},
  {"sortname":"PS","name":"Palestinian Territory Occupied","phonecode":"970"},
  {"sortname":"PA","name":"Panama","phonecode":"507"},
  {"sortname":"PG","name":"Papua new Guinea","phonecode":"675"},
  {"sortname":"PK","name":"Pakistan","phonecode":"92"},
  {"sortname":"PW","name":"Palau","phonecode":"680"},
  {"sortname":"PH","name":"Philippines","phonecode":"63"},
  {"sortname":"PN","name":"Pitcairn Island","phonecode":"0"},
  {"sortname":"PL","name":"Poland","phonecode":"48"},
  {"sortname":"PY","name":"Paraguay","phonecode":"595"},
  {"sortname":"PE","name":"Peru","phonecode":"51"},
  {"sortname":"QA","name":"Qatar","phonecode":"974"},
  {"sortname":"RE","name":"Reunion","phonecode":"262"},
  {"sortname":"RO","name":"Romania","phonecode":"40"},
  {"sortname":"PT","name":"Portugal","phonecode":"351"},
  {"sortname":"PR","name":"Puerto Rico","phonecode":"1787"},
  {"sortname":"SH","name":"Saint Helena","phonecode":"290"},
  {"sortname":"KN","name":"Saint Kitts And Nevis","phonecode":"1869"},
  {"sortname":"LC","name":"Saint Lucia","phonecode":"1758"},
  {"sortname":"RU","name":"Russia","phonecode":"70"},
  {"sortname":"RW","name":"Rwanda","phonecode":"250"},
  {"sortname":"WS","name":"Samoa","phonecode":"684"},
  {"sortname":"SM","name":"San Marino","phonecode":"378"},
  {"sortname":"ST","name":"Sao Tome and Principe","phonecode":"239"},
  {"sortname":"PM","name":"Saint Pierre and Miquelon","phonecode":"508"},
  {"sortname":"VC","name":"Saint Vincent And The Grenadines","phonecode":"1784"},
  {"sortname":"RS","name":"Serbia","phonecode":"381"},
  {"sortname":"SC","name":"Seychelles","phonecode":"248"},
  {"sortname":"SL","name":"Sierra Leone","phonecode":"232"},
  {"sortname":"SA","name":"Saudi Arabia","phonecode":"966"},
  {"sortname":"SN","name":"Senegal","phonecode":"221"},
  {"sortname":"SI","name":"Slovenia","phonecode":"386"},
  {"sortname":"XG","name":"Smaller Territories of the UK","phonecode":"44"},
  {"sortname":"SB","name":"Solomon Islands","phonecode":"677"},
  {"sortname":"SG","name":"Singapore","phonecode":"65"},
  {"sortname":"SK","name":"Slovakia","phonecode":"421"},
  {"sortname":"GS","name":"South Georgia","phonecode":"0"},
  {"sortname":"SS","name":"South Sudan","phonecode":"211"},
  {"sortname":"ES","name":"Spain","phonecode":"34"},
  {"sortname":"SO","name":"Somalia","phonecode":"252"},
  {"sortname":"ZA","name":"South Africa","phonecode":"27"},
  {"sortname":"SR","name":"Suriname","phonecode":"597"},
  {"sortname":"SJ","name":"Svalbard And Jan Mayen Islands","phonecode":"47"},
  {"sortname":"LK","name":"Sri Lanka","phonecode":"94"},
  {"sortname":"SZ","name":"Swaziland","phonecode":"268"},
  {"sortname":"SY","name":"Syria","phonecode":"963"},
  {"sortname":"SD","name":"Sudan","phonecode":"249"},
  {"sortname":"SE","name":"Sweden","phonecode":"46"},
  {"sortname":"TW","name":"Taiwan","phonecode":"886"},
  {"sortname":"TJ","name":"Tajikistan","phonecode":"992"},
  {"sortname":"TG","name":"Togo","phonecode":"228"},
  {"sortname":"CH","name":"Switzerland","phonecode":"41"},
  {"sortname":"TK","name":"Tokelau","phonecode":"690"},
  {"sortname":"TR","name":"Turkey","phonecode":"90"},
  {"sortname":"TZ","name":"Tanzania","phonecode":"255"},
  {"sortname":"TH","name":"Thailand","phonecode":"66"},
  {"sortname":"TO","name":"Tonga","phonecode":"676"},
  {"sortname":"UA","name":"Ukraine","phonecode":"380"},
  {"sortname":"TM","name":"Turkmenistan","phonecode":"7370"},
  {"sortname":"TN","name":"Tunisia","phonecode":"216"},
  {"sortname":"TT","name":"Trinidad And Tobago","phonecode":"1868"},
  {"sortname":"UY","name":"Uruguay","phonecode":"598"},
  {"sortname":"TC","name":"Turks And Caicos Islands","phonecode":"1649"},
  {"sortname":"AE","name":"United Arab Emirates","phonecode":"971"},
  {"sortname":"UG","name":"Uganda","phonecode":"256"},
  {"sortname":"TV","name":"Tuvalu","phonecode":"688"},
  {"sortname":"VN","name":"Vietnam","phonecode":"84"},
  {"sortname":"UM","name":"United States Minor Outlying Islands","phonecode":"1"},
  {"sortname":"UZ","name":"Uzbekistan","phonecode":"998"},
  {"sortname":"VU","name":"Vanuatu","phonecode":"678"},
  {"sortname":"VE","name":"Venezuela","phonecode":"58"},
  {"sortname":"VG","name":"Virgin Islands (British)","phonecode":"1284"},
  {"sortname":"YE","name":"Yemen","phonecode":"967"},
  {"sortname":"VA","name":"Vatican City State (Holy See)","phonecode":"39"},
  {"sortname":"VI","name":"Virgin Islands (US)","phonecode":"1340"},
  {"sortname":"EH","name":"Western Sahara","phonecode":"212"},
  {"sortname":"YU","name":"Yugoslavia","phonecode":"38"},
  {"sortname":"WF","name":"Wallis And Futuna Islands","phonecode":"681"},
  {"sortname":"ZM","name":"Zambia","phonecode":"260"},
  {"sortname":"ZW","name":"Zimbabwe","phonecode":"263"}
]
